project:
  type: website
  output-dir: ../docs
  render:
    - index.qmd
    - hintikkaxo_presentation.qmd
    - intro.qmd
    - bioconductor.qmd
    - starting.qmd
    - reproducible_workflow.qmd
    - datacontainers.qmd
    - summarizedexperiment.qmd
    - day2.qmd
    - treese.qmd
    - tengeler2020_presentation.qmd
    - tengeler_quarto.qmd
    - tengeler_basic_exploration.qmd
    - tengeler_alpha_diversity.qmd
    - tengeler_pcoa.qmd
    - tengeler_dbrda.qmd
    - tengeler_community_composition.qmd
    - tengeler_differential_abundance.qmd
